server:
  port: 7901

spring:
  application:
    name: consumer-movie

# eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://smalle:smalle@localhost:8761/eureka/
  instance:
    # 启用ip访问
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}