server:
  port: 8000

spring:
  application:
    name: provider-user # 建议小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
#  cloud:
#    stream:
#      bindings:
#        input:
#          producer:
#            # 可根据实际消息规则配置SpEL表达式生成分区键用于分配出站数据, 用于消息分区
#            partitionKeyExpression: payload
#            # 分区数量
#            partitionCount: 2


logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG

# eureka客户端配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://smalle:smalle@localhost:8761/eureka/
  instance:
    # 启用ip访问
    prefer-ip-address: true
    # 实例id
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

endpoints:
  env:
    # env端点默认不公开，此时设置为可公开方法
    sensitive: false
